### ISSUE TITLE
use of (sampleTerrainMostDetailed) insted of (sampleTerrain) 

### ISSUE THREAD

**Issue by baloola** [jimmyangel/sampleterrain#1]
Hi there,
I've used this tool and it works great for me. However, in my clone I have replaced  (sampleTerrain) with this new function [sampleTerrainMostDetailed](https://cesiumjs.org/Cesium/Build/Documentation/sampleTerrainMostDetailed.html). It is better since sometimes the level (default 11)  is not available/known for every area.
again, thanks for the nice tool :)

**Comment by jimmyangel** [comment]
Hey, that's cool. Do you want to do a Pull Request?

**Comment by baloola** [comment]
That will be great

**Comment by jimmyangel** [comment]
This is easier to use. Thank you for your contribution.
