### ISSUE TITLE
Height value is undefined

### ISSUE THREAD

**Issue by predictwise** [jimmyangel/sampleterrain#7]
Hi @jimmyangel,

I got the following error:
```
node sampleterrain.js -f data.json -t 'my Cesium Ion token'  > sampled.json

Sample terrain error TypeError: Cannot read property 'toFixed' of undefined
    at /home/geostud/oliverProjects/sampleterrain-master/lib/index.js:39:119
    at Array.forEach (<anonymous>)
    at /home/geostud/oliverProjects/sampleterrain-master/lib/index.js:37:19
    at Promise$1.then (/home/geostud/oliverProjects/sampleterrain-master/node_modules/cesium/Build/CesiumUnminified/Cesium.js:12630:36)
    at /home/geostud/oliverProjects/sampleterrain-master/node_modules/cesium/Build/CesiumUnminified/Cesium.js:12731:15
    at processQueue (/home/geostud/oliverProjects/sampleterrain-master/node_modules/cesium/Build/CesiumUnminified/Cesium.js:13081:6)
    at _resolve (/home/geostud/oliverProjects/sampleterrain-master/node_modules/cesium/Build/CesiumUnminified/Cesium.js:12767:6)
    at promiseResolve (/home/geostud/oliverProjects/sampleterrain-master/node_modules/cesium/Build/CesiumUnminified/Cesium.js:12793:13)
    at Promise$1.then (/home/geostud/oliverProjects/sampleterrain-master/node_modules/cesium/Build/CesiumUnminified/Cesium.js:12630:36)
    at /home/geostud/oliverProjects/sampleterrain-master/node_modules/cesium/Build/CesiumUnminified/Cesium.js:12731:15
```

This is because the some height values are undefined.

If I take a smaller data.json as input, the code can be executed successfully and smoothly. Hence, I guess this might be relative to my data size? `Cesium.sampleTerrain` can not process such an amount of data at the same time?

Oliver

**Comment by jimmyangel** [comment]
It is possible for Cesium sampleTerrain to return undefined for coordinates where terrain data is not available. Looks like I never took that possibility into account. I could make a small fix later and return undefined for those coordinates instead of just crashing.

**Comment by predictwise** [comment]
Hi @jimmyangel,

I found out the error was not caused by no terrain data, but sending too many requests at one time. `CesiumTerrainProvider.requestTileGeometry(x, y, level)` returns undefined instead of a promise for each request.

Hence, I wanna split my data into batches(e.g 1000 per batch) and send one batch each time. But I don't know how to implement it because `Cesium.sampleTerrain()` returns a promise and I need to wait for promise finishing his job and then send the next batch.

Here is my example code:
```
var tp = new Cesium.CesiumTerrainProvider({url: options.terrainProviderUrl});

var j;
for(j=0;j<positions.length;){
  var tmp_positions = positions.slice(j, j+=1000);

  var sampleTerrain = Cesium.sampleTerrain(tp, options.level, tmp_positions);
  Cesium.when(sampleTerrain, function () {
    var cnt11 = 0;
    var cnt22 = 0;

    for(var i=0;i<tmp_positions.length; i++){
      if (tmp_positions[i].height !== undefined) {
        cnt11++;
      }
      else {
        cnt22++;
      }

    }

    console.log('cnt11: ', cnt11);
    console.log('cnt22: ', cnt22);

  });
}
```

Could you give me some hints?

Oliver

**Comment by jimmyangel** [comment]
How big is the file you are trying to process (how many coordinates)? I have tested this with pretty big geojson files (~5MB).

To process promises in a loop, you could use async/await. Put the sample terrain part in an async function and wrap in a standard promise as Cesium uses its own separate promises library.

**Comment by jimmyangel** [comment]
Ok, I made a small change to avoid crashing if cesium returns an undefined height, which is actually possible. Give it a try to see how it goes.

As far as size, the test suite includes a file with 160,000 coordinates, and it works fine.

**Comment by predictwise** [comment]
Hi @jimmyangel,

Thanks for your hint. I've successfully fixed my problem by using async/await right now.

PS: My file has around 340,000 coordinates (~12MB).

Oliver
